apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comfyui.comfyuiName" . }}
  labels:
{{ include "comfyui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "comfyui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "comfyui.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
{{ toYaml .Values.comfyui.affinity | nindent 8 }}
      containers:
        - name: comfyui
          image: "{{ .Values.comfyui.image.repository }}:{{ .Values.comfyui.image.tag }}"
          imagePullPolicy: {{ .Values.comfyui.image.pullPolicy }}
          ports:
{{- range .Values.comfyui.service.ports }}
            - containerPort: {{ .targetPort }}
{{- end }}
          {{- if .Values.comfyui.gpu.enabled }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.comfyui.gpu.num }}
          {{- end }}
          env:
            {{- if .Values.comfyui.env }}
            {{ toYaml .Values.comfyui.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.comfyui.storage.mountPath }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
