apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comfyui.comfyuiName" . }}
  labels:
{{ toYaml (include "comfyui.labels" . | fromYaml) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ toYaml (include "comfyui.selectorLabels" . | fromYaml) | indent 6 }}
  template:
    metadata:
      labels:
{{ toYaml (include "comfyui.selectorLabels" . | fromYaml) | indent 8 }}
    spec:
      {{- with .Values.comfyui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: comfyui
          image: "{{ .Values.comfyui.image.repository }}:{{ .Values.comfyui.image.tag }}"
          imagePullPolicy: {{ .Values.comfyui.image.pullPolicy }}
          ports:
            - containerPort: 8188
          {{- if .Values.comfyui.gpu.enabled }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.comfyui.gpu.num }}
          {{- end }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.comfyui.storage.mountPath }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
