{{- if .Values.comfyui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comfyui.comfyuiName" . }}
  labels:
{{ include "comfyui.labels" . | nindent 4 }}
  annotations:
{{ include "comfyui.ingressAnnotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.comfyui.ingress.className }}
  rules:
    - host: {{ .Values.comfyui.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "comfyui.comfyuiName" . }}
                port:
                  number: 8188
  {{- if .Values.comfyui.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.comfyui.ingress.hostname }}
      secretName: {{ .Values.comfyui.ingress.tls.secretName }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comfyui.comfyuiName" . }}-code
  labels:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.comfyui.ingress.className }}
  rules:
    - host: {{ .Values.comfyui.ingress.hostname }}
      http:
        paths:
          - path: /code(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "comfyui.comfyuiName" . }}
                port:
                  number: 8080
{{- end }}
