{{- if .Values.comfyui.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
  labels:
{{ include "comfyui.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ include "comfyui.storageAccessMode" . }}
  resources:
    requests:
      storage: {{ .Values.comfyui.storage.size }}
  {{- if .Values.comfyui.storage.storageClass }}
  storageClassName: {{ .Values.comfyui.storage.storageClass }}
  {{- end }}
{{- end }}
