apiVersion: v1
kind: Service
metadata:
  name: {{ include "comfyui.comfyuiName" . }}
  labels:
{{ include "comfyui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.comfyui.service.type }}
  selector:
{{ include "comfyui.selectorLabels" . | nindent 4 }}
  ports:
{{- range .Values.comfyui.service.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
