
image:
  repository: yanwk/comfyui-boot
  tag: cu121
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8188

resources:
  limits:
    nvidia.com/gpu: 1

storage:
  enabled: true
  mountPath: /home/runner
  existingClaim: ""
  size: 10Gi
  storageClass: ""

ingress:
  enabled: true
  className: ""
  hostname: comfyui.local
  tls:
    enabled: false
    secretName: ""
