apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: comfyui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8188
          {{- if .Values.gpu.enabled }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.gpu.num }}
          {{- end }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.storage.mountPath }}
        {{- if .Values.filebrowser.enabled }}
        - name: filebrowser
          image: {{ .Values.filebrowser.image }}
          ports:
            - containerPort: {{ .Values.filebrowser.port }}
          volumeMounts:
            - name: storage
              mountPath: /srv
          env:
            - name: FB_AUTH
              value: "{{ .Values.filebrowser.auth.username }}:{{ .Values.filebrowser.auth.password }}"
        {{- end }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.storage.existingClaim | default "comfyui-pvc" }}
