apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      affinity:
        {{- toYaml .Values.comfyui.affinity | nindent 8 }}
      containers:
        - name: comfyui
          image: "{{ .Values.comfyui.image.repository }}:{{ .Values.comfyui.image.tag }}"
          imagePullPolicy: {{ .Values.comfyui.image.pullPolicy }}
          ports:
            - containerPort: 8188
          {{- if .Values.comfyui.gpu.enabled }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.comfyui.gpu.num }}
          {{- end }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.comfyui.storage.mountPath }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
