{{- if .Values.comfyui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui
spec:
  ingressClassName: {{ .Values.comfyui.ingress.className }}
  rules:
    - host: {{ .Values.comfyui.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comfyui
                port:
                  number: {{ .Values.comfyui.service.port }}
  {{- if .Values.comfyui.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.comfyui.ingress.hostname }}
      secretName: {{ .Values.comfyui.ingress.tls.secretName }}
  {{- end }}
{{- end }}
