apiVersion: v1
kind: Service
metadata:
  name: comfyui
spec:
  type: {{ .Values.comfyui.service.type }}
  selector:
    app: comfyui
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.comfyui.service.port }}
      targetPort: 8188
