apiVersion: v1
kind: Service
metadata:
  name: {{ include "comfyui.comfyuiName" . }}
  labels:
{{ toYaml (include "comfyui.labels" . | fromYaml) | indent 4 }}
spec:
  type: {{ .Values.comfyui.service.type }}
  selector:
{{ toYaml (include "comfyui.selectorLabels" . | fromYaml) | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.comfyui.service.port }}
      targetPort: 8188
