{{- if .Values.filebrowser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comfyui.filebrowserName" . }}
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "comfyui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "comfyui.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: filebrowser-init
          image: {{ .Values.filebrowser.image }}
          command:
            - /bin/sh
            - -c
            - |
              filebrowser config init
              filebrowser users add {{ .Values.filebrowser.auth.username }} {{ .Values.filebrowser.auth.password }} --perm.admin
              cp -r /database /srv/.filebrowser
          volumeMounts:
            - name: storage
              mountPath: /srv
      containers:
        - name: filebrowser
          image: {{ .Values.filebrowser.image }}
          args:
            - "--baseurl"
            - "{{ .Values.filebrowser.baseurl }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage
              mountPath: /srv
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
{{- end }}
