{{- if .Values.filebrowser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comfyui.filebrowserName" . }}
  labels:
{{ include "comfyui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "comfyui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "comfyui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: filebrowser
          image: {{ .Values.filebrowser.image }}
          args:
            - "--baseurl"
            - "{{ .Values.filebrowser.baseurl }}"
          envFrom:
            - secretRef:
                name: {{ include "comfyui.filebrowserName" . }}-auth
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage
              mountPath: /srv
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
{{- end }}
