{{- if .Values.filebrowser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      initContainers:
        - name: create-user
          image: {{ .Values.filebrowser.image }}
          command: ["/bin/sh", "-c"]
          args:
            - >-
              filebrowser config init &&
              filebrowser users add {{ .Values.filebrowser.auth.username }} {{ .Values.filebrowser.auth.password }} /srv
          volumeMounts:
            - name: storage
              mountPath: /srv
      containers:
        - name: filebrowser
          image: {{ .Values.filebrowser.image }}
          args:
            - "--baseurl"
            - "{{ .Values.filebrowser.baseurl }}"
          ports:
            - containerPort: {{ .Values.filebrowser.service.port }}
          volumeMounts:
            - name: storage
              mountPath: /srv
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
{{- end }}
