{{- if .Values.filebrowser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: {{ .Values.filebrowser.image }}
          ports:
            - containerPort: {{ .Values.filebrowser.service.port }}
          volumeMounts:
            - name: storage
              mountPath: /srv
          env:
            - name: FB_AUTH
              value: "{{ .Values.filebrowser.auth.username }}:{{ .Values.filebrowser.auth.password }}"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.comfyui.storage.existingClaim | default "comfyui-pvc" }}
{{- end }}
