{{- if .Values.filebrowser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  type: {{ .Values.filebrowser.service.type }}
  selector:
    app: filebrowser
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.filebrowser.service.port }}
      targetPort: {{ .Values.filebrowser.service.port }}
{{- end }}
